// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

/**
 * <pre>
 * 客户端向 follower 节点注册服务
 * </pre>
 *
 * Protobuf type {@code DMQFollower.ClientRegistToFollower}
 */
public final class ClientRegistToFollower extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DMQFollower.ClientRegistToFollower)
    ClientRegistToFollowerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientRegistToFollower.newBuilder() to construct.
  private ClientRegistToFollower(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientRegistToFollower() {
    nodeid_ = "";
    groupname_ = "";
    topic_ = "";
    key_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientRegistToFollower();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientRegistToFollower(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            groupname_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_ClientRegistToFollower_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_ClientRegistToFollower_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.liangchen.DMQFollowerProto.ClientRegistToFollower.class, com.liangchen.DMQFollowerProto.ClientRegistToFollower.Builder.class);
  }

  public static final int NODEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object nodeid_;
  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The nodeid.
   */
  @java.lang.Override
  public java.lang.String getNodeid() {
    java.lang.Object ref = nodeid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The bytes for nodeid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeidBytes() {
    java.lang.Object ref = nodeid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object groupname_;
  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The groupname.
   */
  @java.lang.Override
  public java.lang.String getGroupname() {
    java.lang.Object ref = groupname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupname_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The bytes for groupname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupnameBytes() {
    java.lang.Object ref = groupname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 3;
  private volatile java.lang.Object topic_;
  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object key_;
  /**
   * <pre>
   * 密钥
   * </pre>
   *
   * <code>string key = 4;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 密钥
   * </pre>
   *
   * <code>string key = 4;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNodeidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeid_);
    }
    if (!getGroupnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupname_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, key_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNodeidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeid_);
    }
    if (!getGroupnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupname_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, key_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.liangchen.DMQFollowerProto.ClientRegistToFollower)) {
      return super.equals(obj);
    }
    com.liangchen.DMQFollowerProto.ClientRegistToFollower other = (com.liangchen.DMQFollowerProto.ClientRegistToFollower) obj;

    if (!getNodeid()
        .equals(other.getNodeid())) return false;
    if (!getGroupname()
        .equals(other.getGroupname())) return false;
    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeid().hashCode();
    hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGroupname().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.liangchen.DMQFollowerProto.ClientRegistToFollower prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 客户端向 follower 节点注册服务
   * </pre>
   *
   * Protobuf type {@code DMQFollower.ClientRegistToFollower}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DMQFollower.ClientRegistToFollower)
      com.liangchen.DMQFollowerProto.ClientRegistToFollowerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_ClientRegistToFollower_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_ClientRegistToFollower_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liangchen.DMQFollowerProto.ClientRegistToFollower.class, com.liangchen.DMQFollowerProto.ClientRegistToFollower.Builder.class);
    }

    // Construct using com.liangchen.DMQFollowerProto.ClientRegistToFollower.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeid_ = "";

      groupname_ = "";

      topic_ = "";

      key_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_ClientRegistToFollower_descriptor;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.ClientRegistToFollower getDefaultInstanceForType() {
      return com.liangchen.DMQFollowerProto.ClientRegistToFollower.getDefaultInstance();
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.ClientRegistToFollower build() {
      com.liangchen.DMQFollowerProto.ClientRegistToFollower result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.ClientRegistToFollower buildPartial() {
      com.liangchen.DMQFollowerProto.ClientRegistToFollower result = new com.liangchen.DMQFollowerProto.ClientRegistToFollower(this);
      result.nodeid_ = nodeid_;
      result.groupname_ = groupname_;
      result.topic_ = topic_;
      result.key_ = key_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.liangchen.DMQFollowerProto.ClientRegistToFollower) {
        return mergeFrom((com.liangchen.DMQFollowerProto.ClientRegistToFollower)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.liangchen.DMQFollowerProto.ClientRegistToFollower other) {
      if (other == com.liangchen.DMQFollowerProto.ClientRegistToFollower.getDefaultInstance()) return this;
      if (!other.getNodeid().isEmpty()) {
        nodeid_ = other.nodeid_;
        onChanged();
      }
      if (!other.getGroupname().isEmpty()) {
        groupname_ = other.groupname_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.liangchen.DMQFollowerProto.ClientRegistToFollower parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.liangchen.DMQFollowerProto.ClientRegistToFollower) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object nodeid_ = "";
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>string nodeid = 1;</code>
     * @return The nodeid.
     */
    public java.lang.String getNodeid() {
      java.lang.Object ref = nodeid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>string nodeid = 1;</code>
     * @return The bytes for nodeid.
     */
    public com.google.protobuf.ByteString
        getNodeidBytes() {
      java.lang.Object ref = nodeid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>string nodeid = 1;</code>
     * @param value The nodeid to set.
     * @return This builder for chaining.
     */
    public Builder setNodeid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>string nodeid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeid() {
      
      nodeid_ = getDefaultInstance().getNodeid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 节点id
     * </pre>
     *
     * <code>string nodeid = 1;</code>
     * @param value The bytes for nodeid to set.
     * @return This builder for chaining.
     */
    public Builder setNodeidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object groupname_ = "";
    /**
     * <pre>
     * 消费者组名
     * </pre>
     *
     * <code>string groupname = 2;</code>
     * @return The groupname.
     */
    public java.lang.String getGroupname() {
      java.lang.Object ref = groupname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消费者组名
     * </pre>
     *
     * <code>string groupname = 2;</code>
     * @return The bytes for groupname.
     */
    public com.google.protobuf.ByteString
        getGroupnameBytes() {
      java.lang.Object ref = groupname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消费者组名
     * </pre>
     *
     * <code>string groupname = 2;</code>
     * @param value The groupname to set.
     * @return This builder for chaining.
     */
    public Builder setGroupname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupname_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消费者组名
     * </pre>
     *
     * <code>string groupname = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupname() {
      
      groupname_ = getDefaultInstance().getGroupname();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消费者组名
     * </pre>
     *
     * <code>string groupname = 2;</code>
     * @param value The bytes for groupname to set.
     * @return This builder for chaining.
     */
    public Builder setGroupnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <pre>
     * 话题名称
     * </pre>
     *
     * <code>string topic = 3;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 话题名称
     * </pre>
     *
     * <code>string topic = 3;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 话题名称
     * </pre>
     *
     * <code>string topic = 3;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 话题名称
     * </pre>
     *
     * <code>string topic = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 话题名称
     * </pre>
     *
     * <code>string topic = 3;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <pre>
     * 密钥
     * </pre>
     *
     * <code>string key = 4;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 密钥
     * </pre>
     *
     * <code>string key = 4;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 密钥
     * </pre>
     *
     * <code>string key = 4;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密钥
     * </pre>
     *
     * <code>string key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 密钥
     * </pre>
     *
     * <code>string key = 4;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DMQFollower.ClientRegistToFollower)
  }

  // @@protoc_insertion_point(class_scope:DMQFollower.ClientRegistToFollower)
  private static final com.liangchen.DMQFollowerProto.ClientRegistToFollower DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.liangchen.DMQFollowerProto.ClientRegistToFollower();
  }

  public static com.liangchen.DMQFollowerProto.ClientRegistToFollower getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientRegistToFollower>
      PARSER = new com.google.protobuf.AbstractParser<ClientRegistToFollower>() {
    @java.lang.Override
    public ClientRegistToFollower parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientRegistToFollower(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientRegistToFollower> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientRegistToFollower> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.liangchen.DMQFollowerProto.ClientRegistToFollower getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

