// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

public interface ClientRegistToFollowerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.ClientRegistToFollower)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The nodeid.
   */
  String getNodeid();
  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The bytes for nodeid.
   */
  com.google.protobuf.ByteString
      getNodeidBytes();

  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The groupname.
   */
  String getGroupname();
  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The bytes for groupname.
   */
  com.google.protobuf.ByteString
      getGroupnameBytes();

  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * 密钥
   * </pre>
   *
   * <code>string key = 4;</code>
   * @return The key.
   */
  String getKey();
  /**
   * <pre>
   * 密钥
   * </pre>
   *
   * <code>string key = 4;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
