// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

import com.google.protobuf.ByteString;
import com.google.protobuf.MessageOrBuilder;

public interface ClientRegistToFollowerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.ClientRegistToFollower)
        MessageOrBuilder {

  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The nodeid.
   */
  java.lang.String getNodeid();
  /**
   * <pre>
   * 节点id
   * </pre>
   *
   * <code>string nodeid = 1;</code>
   * @return The bytes for nodeid.
   */
  ByteString
      getNodeidBytes();

  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The groupname.
   */
  java.lang.String getGroupname();
  /**
   * <pre>
   * 消费者组名
   * </pre>
   *
   * <code>string groupname = 2;</code>
   * @return The bytes for groupname.
   */
  ByteString
      getGroupnameBytes();

  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * 话题名称
   * </pre>
   *
   * <code>string topic = 3;</code>
   * @return The bytes for topic.
   */
  ByteString
      getTopicBytes();
}
