// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

public interface FollowerRegistToHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.FollowerRegistToHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 绑定的ip 地址
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The address.
   */
  String getAddress();
  /**
   * <pre>
   * 绑定的ip 地址
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * 绑定的 端口
   * </pre>
   *
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();
}
