// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

import com.google.protobuf.*;

/**
 * <pre>
 *follower 向 header 注册服务
 * </pre>
 *
 * Protobuf type {@code DMQFollower.FollowerRegistToHeader}
 */
public final class FollowerRegistToHeader extends
        GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DMQFollower.FollowerRegistToHeader)
    FollowerRegistToHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FollowerRegistToHeader.newBuilder() to construct.
  private FollowerRegistToHeader(GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FollowerRegistToHeader() {
    address_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FollowerRegistToHeader();
  }

  @java.lang.Override
  public final UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FollowerRegistToHeader(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 16: {

            port_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final Descriptors.Descriptor
      getDescriptor() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_FollowerRegistToHeader_descriptor;
  }

  @java.lang.Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_FollowerRegistToHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.liangchen.DMQFollowerProto.FollowerRegistToHeader.class, com.liangchen.DMQFollowerProto.FollowerRegistToHeader.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object address_;
  /**
   * <pre>
   * 绑定的ip 地址
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 绑定的ip 地址
   * </pre>
   *
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private int port_;
  /**
   * <pre>
   * 绑定的 端口
   * </pre>
   *
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  @java.lang.Override
  public int getPort() {
    return port_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
    }
    if (port_ != 0) {
      output.writeInt32(2, port_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, port_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.liangchen.DMQFollowerProto.FollowerRegistToHeader)) {
      return super.equals(obj);
    }
    com.liangchen.DMQFollowerProto.FollowerRegistToHeader other = (com.liangchen.DMQFollowerProto.FollowerRegistToHeader) obj;

    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.liangchen.DMQFollowerProto.FollowerRegistToHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *follower 向 header 注册服务
   * </pre>
   *
   * Protobuf type {@code DMQFollower.FollowerRegistToHeader}
   */
  public static final class Builder extends
          GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DMQFollower.FollowerRegistToHeader)
      com.liangchen.DMQFollowerProto.FollowerRegistToHeaderOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_FollowerRegistToHeader_descriptor;
    }

    @java.lang.Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_FollowerRegistToHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liangchen.DMQFollowerProto.FollowerRegistToHeader.class, com.liangchen.DMQFollowerProto.FollowerRegistToHeader.Builder.class);
    }

    // Construct using com.liangchen.DMQFollowerProto.FollowerRegistToHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      address_ = "";

      port_ = 0;

      return this;
    }

    @java.lang.Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_FollowerRegistToHeader_descriptor;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.FollowerRegistToHeader getDefaultInstanceForType() {
      return com.liangchen.DMQFollowerProto.FollowerRegistToHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.FollowerRegistToHeader build() {
      com.liangchen.DMQFollowerProto.FollowerRegistToHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.FollowerRegistToHeader buildPartial() {
      com.liangchen.DMQFollowerProto.FollowerRegistToHeader result = new com.liangchen.DMQFollowerProto.FollowerRegistToHeader(this);
      result.address_ = address_;
      result.port_ = port_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.liangchen.DMQFollowerProto.FollowerRegistToHeader) {
        return mergeFrom((com.liangchen.DMQFollowerProto.FollowerRegistToHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.liangchen.DMQFollowerProto.FollowerRegistToHeader other) {
      if (other == com.liangchen.DMQFollowerProto.FollowerRegistToHeader.getDefaultInstance()) return this;
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.liangchen.DMQFollowerProto.FollowerRegistToHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        parsedMessage = (com.liangchen.DMQFollowerProto.FollowerRegistToHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <pre>
     * 绑定的ip 地址
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        ByteString bs =
            (ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 绑定的ip 地址
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    public ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * 绑定的ip 地址
     * </pre>
     *
     * <code>string address = 1;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 绑定的ip 地址
     * </pre>
     *
     * <code>string address = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 绑定的ip 地址
     * </pre>
     *
     * <code>string address = 1;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <pre>
     * 绑定的 端口
     * </pre>
     *
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <pre>
     * 绑定的 端口
     * </pre>
     *
     * <code>int32 port = 2;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 绑定的 端口
     * </pre>
     *
     * <code>int32 port = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DMQFollower.FollowerRegistToHeader)
  }

  // @@protoc_insertion_point(class_scope:DMQFollower.FollowerRegistToHeader)
  private static final com.liangchen.DMQFollowerProto.FollowerRegistToHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.liangchen.DMQFollowerProto.FollowerRegistToHeader();
  }

  public static com.liangchen.DMQFollowerProto.FollowerRegistToHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final Parser<FollowerRegistToHeader>
      PARSER = new AbstractParser<FollowerRegistToHeader>() {
    @java.lang.Override
    public FollowerRegistToHeader parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return new FollowerRegistToHeader(input, extensionRegistry);
    }
  };

  public static Parser<FollowerRegistToHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public Parser<FollowerRegistToHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.liangchen.DMQFollowerProto.FollowerRegistToHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

