// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

import com.google.protobuf.*;

/**
 * Protobuf type {@code DMQFollower.MessageData}
 */
public final class MessageData extends
        GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DMQFollower.MessageData)
    MessageDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageData.newBuilder() to construct.
  private MessageData(GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageData() {
    topic_ = "";
    message_ = "";
    des_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageData();
  }

  @java.lang.Override
  public final UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageData(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 24: {

            length_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            des_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final Descriptors.Descriptor
      getDescriptor() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_MessageData_descriptor;
  }

  @java.lang.Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_MessageData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.liangchen.DMQFollowerProto.MessageData.class, com.liangchen.DMQFollowerProto.MessageData.Builder.class);
  }

  public static final int TOPIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object topic_;
  /**
   * <pre>
   * 数据对应的topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 数据对应的topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * 真正的数据
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 真正的数据
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  public static final int LENGTH_FIELD_NUMBER = 3;
  private long length_;
  /**
   * <code>int64 length = 3;</code>
   * @return The length.
   */
  @java.lang.Override
  public long getLength() {
    return length_;
  }

  public static final int DES_FIELD_NUMBER = 4;
  private volatile java.lang.Object des_;
  /**
   * <pre>
   * 附加信息
   * </pre>
   *
   * <code>string des = 4;</code>
   * @return The des.
   */
  @java.lang.Override
  public java.lang.String getDes() {
    java.lang.Object ref = des_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      des_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 附加信息
   * </pre>
   *
   * <code>string des = 4;</code>
   * @return The bytes for des.
   */
  @java.lang.Override
  public ByteString
      getDesBytes() {
    java.lang.Object ref = des_;
    if (ref instanceof java.lang.String) {
      ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      des_ = b;
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (length_ != 0L) {
      output.writeInt64(3, length_);
    }
    if (!getDesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, des_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, length_);
    }
    if (!getDesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, des_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.liangchen.DMQFollowerProto.MessageData)) {
      return super.equals(obj);
    }
    com.liangchen.DMQFollowerProto.MessageData other = (com.liangchen.DMQFollowerProto.MessageData) obj;

    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getLength()
        != other.getLength()) return false;
    if (!getDes()
        .equals(other.getDes())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (37 * hash) + DES_FIELD_NUMBER;
    hash = (53 * hash) + getDes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.liangchen.DMQFollowerProto.MessageData parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.liangchen.DMQFollowerProto.MessageData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DMQFollower.MessageData}
   */
  public static final class Builder extends
          GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DMQFollower.MessageData)
      com.liangchen.DMQFollowerProto.MessageDataOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_MessageData_descriptor;
    }

    @java.lang.Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liangchen.DMQFollowerProto.MessageData.class, com.liangchen.DMQFollowerProto.MessageData.Builder.class);
    }

    // Construct using com.liangchen.DMQFollowerProto.MessageData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      topic_ = "";

      message_ = "";

      length_ = 0L;

      des_ = "";

      return this;
    }

    @java.lang.Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return com.liangchen.DMQFollowerProto.DMQFollowerProto.internal_static_DMQFollower_MessageData_descriptor;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.MessageData getDefaultInstanceForType() {
      return com.liangchen.DMQFollowerProto.MessageData.getDefaultInstance();
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.MessageData build() {
      com.liangchen.DMQFollowerProto.MessageData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.liangchen.DMQFollowerProto.MessageData buildPartial() {
      com.liangchen.DMQFollowerProto.MessageData result = new com.liangchen.DMQFollowerProto.MessageData(this);
      result.topic_ = topic_;
      result.message_ = message_;
      result.length_ = length_;
      result.des_ = des_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.liangchen.DMQFollowerProto.MessageData) {
        return mergeFrom((com.liangchen.DMQFollowerProto.MessageData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.liangchen.DMQFollowerProto.MessageData other) {
      if (other == com.liangchen.DMQFollowerProto.MessageData.getDefaultInstance()) return this;
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      if (!other.getDes().isEmpty()) {
        des_ = other.des_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.liangchen.DMQFollowerProto.MessageData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        parsedMessage = (com.liangchen.DMQFollowerProto.MessageData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <pre>
     * 数据对应的topic
     * </pre>
     *
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        ByteString bs =
            (ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 数据对应的topic
     * </pre>
     *
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    public ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * 数据对应的topic
     * </pre>
     *
     * <code>string topic = 1;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据对应的topic
     * </pre>
     *
     * <code>string topic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据对应的topic
     * </pre>
     *
     * <code>string topic = 1;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * 真正的数据
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        ByteString bs =
            (ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 真正的数据
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * 真正的数据
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 真正的数据
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 真正的数据
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <code>int64 length = 3;</code>
     * @return The length.
     */
    @java.lang.Override
    public long getLength() {
      return length_;
    }
    /**
     * <code>int64 length = 3;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 length = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      
      length_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object des_ = "";
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>string des = 4;</code>
     * @return The des.
     */
    public java.lang.String getDes() {
      java.lang.Object ref = des_;
      if (!(ref instanceof java.lang.String)) {
        ByteString bs =
            (ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        des_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>string des = 4;</code>
     * @return The bytes for des.
     */
    public ByteString
        getDesBytes() {
      java.lang.Object ref = des_;
      if (ref instanceof String) {
        ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        des_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>string des = 4;</code>
     * @param value The des to set.
     * @return This builder for chaining.
     */
    public Builder setDes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      des_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>string des = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDes() {
      
      des_ = getDefaultInstance().getDes();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>string des = 4;</code>
     * @param value The bytes for des to set.
     * @return This builder for chaining.
     */
    public Builder setDesBytes(
        ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  AbstractMessageLite.checkByteStringIsUtf8(value);
      
      des_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DMQFollower.MessageData)
  }

  // @@protoc_insertion_point(class_scope:DMQFollower.MessageData)
  private static final com.liangchen.DMQFollowerProto.MessageData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.liangchen.DMQFollowerProto.MessageData();
  }

  public static com.liangchen.DMQFollowerProto.MessageData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final Parser<MessageData>
      PARSER = new AbstractParser<MessageData>() {
    @java.lang.Override
    public MessageData parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return new MessageData(input, extensionRegistry);
    }
  };

  public static Parser<MessageData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public Parser<MessageData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.liangchen.DMQFollowerProto.MessageData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

