// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

import com.google.protobuf.ByteString;
import com.google.protobuf.MessageOrBuilder;

public interface MessageDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.MessageData)
        MessageOrBuilder {

  /**
   * <pre>
   * 数据对应的topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * 数据对应的topic
   * </pre>
   *
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  ByteString
      getTopicBytes();

  /**
   * <pre>
   * 真正的数据
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 真正的数据
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  ByteString
      getMessageBytes();

  /**
   * <code>int64 length = 3;</code>
   * @return The length.
   */
  long getLength();

  /**
   * <pre>
   * 附加信息
   * </pre>
   *
   * <code>string des = 4;</code>
   * @return The des.
   */
  java.lang.String getDes();
  /**
   * <pre>
   * 附加信息
   * </pre>
   *
   * <code>string des = 4;</code>
   * @return The bytes for des.
   */
  ByteString
      getDesBytes();
}
