// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 errno = 1;</code>
   * @return The errno.
   */
  int getErrno();

  /**
   * <code>string errmsg = 2;</code>
   * @return The errmsg.
   */
  String getErrmsg();
  /**
   * <code>string errmsg = 2;</code>
   * @return The bytes for errmsg.
   */
  com.google.protobuf.ByteString
      getErrmsgBytes();

  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   * @return The data.
   */
  MessageData getData();
  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   */
  MessageDataOrBuilder getDataOrBuilder();
}
