// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: follower.proto

package com.liangchen.DMQFollowerProto;

import com.google.protobuf.ByteString;
import com.google.protobuf.MessageOrBuilder;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DMQFollower.Response)
        MessageOrBuilder {

  /**
   * <code>int32 errno = 1;</code>
   * @return The errno.
   */
  int getErrno();

  /**
   * <code>string errmsg = 2;</code>
   * @return The errmsg.
   */
  java.lang.String getErrmsg();
  /**
   * <code>string errmsg = 2;</code>
   * @return The bytes for errmsg.
   */
  ByteString
      getErrmsgBytes();

  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   * @return The data.
   */
  com.liangchen.DMQFollowerProto.MessageData getData();
  /**
   * <code>.DMQFollower.MessageData data = 3;</code>
   */
  com.liangchen.DMQFollowerProto.MessageDataOrBuilder getDataOrBuilder();
}
